=== pkompella/java-core-concepts/samples/xml/customers.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2016 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="age">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="29"/>
				<xs:enumeration value="39"/>
				<xs:enumeration value="43"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Customer 1"/>
				<xs:enumeration value="Customer 2"/>
				<xs:enumeration value="Customer 3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="customer">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="age"/>
				<xs:element ref="name"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:short">
						<xs:enumeration value="100"/>
						<xs:enumeration value="200"/>
						<xs:enumeration value="300"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="customers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="customer" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== pkompella/java-core-concepts/samples/xml/customers.xml
<?xml version="1.0" encoding="UTF-8"?>
<customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Workspaces/JavaEE/Training/XmlProcessing/src/customers.xsd">
	<customer id="100">
		<age>29</age>
		<name>Customer 1</name>
	</customer>
	<customer id="200">
		<age>39</age>
		<name>Customer 2</name>
	</customer>
	<customer id="300">
		<age>43</age>
		<name>Customer 3</name>
	</customer>
</customers>
